spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/testmaster?serverTimezone=UTC
      username: root
      password: 111111
      driver-class-name: com.mysql.jdbc.Driver
    slave:
      jdbc-url: jdbc:mysql://localhost:3306/testslave?serverTimezone=UTC
      username: root
      password: 111111
      driver-class-name: com.mysql.jdbc.Driver
mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.zhangxr.springcloud.entities       #所有Entity别名类所在包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



